### ISSUE TITLE
Where to use .constant and add additional external mods?

### ISSUE THREAD

**Issue by jwall** [CaryLandholt/AngularFun#54]
Currently I need to use .constant and add additional external modules. I am accomplishing this by using my own app template like:

<code>angular.module 'app', <%= config.modules %>
angular.module('app.config', []).constant('version', '0.1'))</code>

and by adding an additionalModules key in the Gruntfile for ngShim to concat to config.modules (referring to modules explicitly referenced in index.html and not through requireJS).

Because I have to modify ngShim to do this I was wondering if you had an alternative suggestion or a less intrusive mechanism to accomplish these tasks?

**Comment by CaryLandholt** [comment]
Hi @jwall,

Using ngShim you no longer need an app file.  It's created for you.
So you no longer need to do `angular.module 'app', <%= config.modules %>`.

When including modules other than `app`, you will need to add them to the modules section of ngShim.

As for constants, they can be treated just like any other module type.

``` CoffeeScript
# file:  src/scripts/constants/version.coffee
angular.module('app').constant 'version', '0.1'
```

Let me know if this works.  I may need to tweak the ngShim grunt task a bit.
If you're interested, [here it is](https://github.com/CaryLandholt/grunt-hustler/blob/master/tasks/ngShim.coffee).

Thanks,
Cary

**Comment by jwall** [comment]
In order to get my code to work I modified ngShim so that it grabs my app template with the constants defined. If I don't do it that way the app.config module isn't loaded at the right time. I have tried a version.coffee and also putting the constants in the routes.coffee file, but both fail. (Follow-up: I can use a constants.coffee and not modify the app template, but I still need the additionalModules as described below to include app.config)

Also, because I have external js files loaded via a cdn, the modules array didn't work for me, i.e., I only have a key and no value. So, I added an additionalModules array to make sure the app gets the external js module dependencies.

Lastly, I have a js file that extends a module so there is no module but there is a js dependency.

All, very dirty for your clean setup, but I guess when you rely on third party source this can happen :-)

My ngShim:

```
ngShim:
  scripts:
    cwd: './.temp/scripts/'
    angular: 'libs/angular.min.js'
    angularFire: 'libs/angular-fire.js'
    appTemplatePath: '../../../src/scripts/libs/templates/app.tpl'
    additionalModules: ['app.config', 'firebase']
    modules: [
      'ngAnimate': 'libs/angular-animate.min.js'
      'ngResource': 'libs/angular-resource.min.js'
      'ngRoute': 'libs/angular-route.min.js'
    ]
    src: '**/*.coffee'
    dest: 'main.coffee'
```

where 

<code>angularFire: 'libs/angular-fire.js'</code>

is the module extension (extends the firebase module).

<code>appTemplatePath: '../../../src/scripts/libs/templates/app.tpl'</code>

is to add the constants into the app directly.

<code>additionalModules: ['app.config', 'firebase']</code>

is to handle the external js modules.

**Comment by jwall** [comment]
I refactored the ngShim portion a bit so now it looks like so:

```
ngShim:
  scripts:
    cwd: './.temp/scripts/'
    angular: 'libs/angular.min.js'
    externalModules: ['app.config', 'firebase']
    externalLibs: ['libs/angular-fire.js']
    modules: [
      'ngAnimate': 'libs/angular-animate.min.js'
      'ngResource': 'libs/angular-resource.min.js'
      'ngRoute': 'libs/angular-route.min.js'
      'ui.bootstrap': 'libs/ui-bootstrap-tpls.min.js'
    ]
    src: '**/*.coffee'
    dest: 'main.coffee'
```

so this lets you use modules that are externally loaded (and also my constants issue) and libs that extend a module.
